### ISSUE TITLE
스터디 6주차 인증하기

### ISSUE THREAD

**Issue by LangVE** [daybreak6/docker#6]
## 목표

* 6장. 단일 컨테이너를 활용한 애플리케이션 만들기

**Comment by LangVE** [comment]
6 장 읽었습니다. :sweat_smile:

**Comment by kaiwind7** [comment]
## 06. 단일 컨테이너를 활용한 애플리케이션 개발하기

6장 리액트 앱 개발

7장 리액트 앱 테스트 & 배포 

8장 리액트 & 노드 & 데이터베이스 앱 개발

9장 리액트 & 노드 & 데이터베이스 앱

테스트&배포



### 6.1 리액트 설치 및 애플리케이션 생성

1. 리액트 애플리케이션을 만들 폴더를 생성. 

2. 비주얼 스튜디오 코드를 실행 후 생성 폴더 추가

3. 터미널 실행하고 리액트를 설치할 폴더로 이동한 다음 
   'npx create-react-app ./ 명령어를 입력'

   ```bash
   npx create-react-app ./
   ```

   

4. 설치가 완료됐으면 잘 설치됐는지 확인

   ```bash
   npm run start
   ```

   

#### 리액트 애플리케이션 생성하기

1. 터미널에서 'npm run start' 명렁어를 입력해 리액트 애플리케이션을 실행합니다.
2. 터미널에서 리액트 애플리케이션을 실행하는 명령어를 입력하면 브라우저에서 리액트 애플리케이션이 실행됩니다.
3. 애플리케이션을 테스트할 때는 'npm run test' 명령어를 사용합니다.
   테스트는 원하는 만큼 더 만들 수 있습니다.
4. 마지막으로 리액트 애플리케이션의 배포는 리액트 빌드한 다음 빌드한 파일을 이용해 배포합니다. 빌드 파일을 얻기 위해 'npm run build' 명령어를 입력합니다.
5. 빌드 명령어를 입력하고 나서 docker-react-app 폴더를 보면 build 폴더가 생성돼 있고, build 폴더 안에 빌드 파일이 생성된 모습을 볼 수 있습니다.



### 6.2 리액트 애플리케이션을 위한 도커 파일 작성하기

#### 개발 환경을 위한 도커 파일 작성하기

1. 도커 파일 생성. 개발 환경의 도커 파일이므로 'Dockerfile.dev'

2. Dockerfile.dev 도커 파일 작성

   ```dockerfile
   #책 내용대로 하면 에러가 발생..
   FROM node:alpine
   
   WORKDIR /usr/src/app
   
   COPY package.json ./
   
   
   RUN npm install
   
   # 도커 볼륨 사용하여 실행시 오류가 나서 추가
   RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
   
   COPY ./ ./
   
   CMD ["npm", "run", "start"]
   ```

3. 도커 파일로 이미지를 생성

   ```bash
   docker build ./ #에러 발생
   ```

#### 왜 이런 에러 메시지가 발생했을까?

```bash
#-f 옵션 사용 
#이미지를 빌드할 때 사용할 도커 파일을 지정
docker build -f Dockerfile.dev ./
```

### 6.3 생성된 도커 이미지로 로컬에서 리액트 실행하기

1. -t 옵션을 추가해 이름 지정후 이미지 다시 생성

   ```bas
   docker build -f Dockerfile.dev -t jk/docker-react-app ./
   ```

   

2. 이미지를 다시 빌드했으면 빌드된 이미지를 이용해 컨테이너를 생성

   ```bash
   docker run jk/docker-react-app
   ```

   

3. 실행하면 에러 포트 연결 안해서

4. 포트 매핑과 함께 도커 컨테이너를 실행

   ```bash
   docker run -p 3000:3000 jk/docker-react-app
   ```

5. 에러발생하는데 리엑트 실행할 때는 예외적으로 -it 옵션을 추가해야만 정상적으로 동작

6. -it 옵션 추가

   ```bash
   docker run -it -p 3000:3000 jk/docker-react-app
   ```

   

### 6.4 도커 볼륨을 이용한 소스 코드 변경

#### 도커 볼륨을 사용해 애플리케이션 실행하기

1. 다음과 같이 도커 볼륨을 이용해 애플리케이션을 실행

   ```bash
   docker run -it -p 3000:3000 -v /usr/src/app/node_modules -v $(pwd):/usr/src/app 
   jk/docker-react-app
   ```

2. 브라우저에서 리액트 애플리케이션으로 접속

3. App.js의 소스 코드를 변경

   ```js
   import logo from './logo.svg'
   import './App.css'
   
   function App() {
       return (
           <div className="App">
           	<header className="App-header">
   		        <img src={logo} className="App-logo" alt="logo" />
   				<p>
           			Edit <code>src/App.js</code> and save to reload....
   		        </p>
   		        <a
                       className="App-link"
                       href="https://reactjs.org"
                       target="_blank"
                       ret="noopener noreferrer"
   		        >
           			반갑습니다.
   		        </a>
   			</header>
   		</div>
       );
   }
   
   export default App;
   ```

   

### 6.5 도커 컴포즈로  좀 더 간단하게 애플리케이션 실행하기

#### 도커 컴포즈를 이용해 애플리케이션 실행하기

1. docker-compose-dev.yml 생성

2. docker-compose-dev.yml 파일에 소스 코드 작성

   ```yaml
   # 도커 컴포즈의 버전
   version: "3"
   # 실행하는 컨테이너들을 정의
   services:
   # 서비스 이름
     react:
     # 현 디렉터리에 있는 Dockerfile 사용
       build: 
       # 도커 이미지를 구성하기 위한 파일과 폴더들이 있는 위치
         context: .
         # 도커 파일 어떤 것인지 지정
         dockerfile: Dockerfile.dev
       # 포트 매핑 로컬 포트 : 컨테이너 포트
       ports:
        - "3000:3000"
       # 로컬 머신에 있는 파일들을 매핑
       volumes:
        - /usr/src/app/node_modules
        - ./:/usr/src/app
       stdin_open: true
   ```

3. 도커 컴포즈를 이용해 애플리케이션 실행
   개발 환경 버전을 위한 도커 컴포즈 실행 명령어

   ```bash
   docker-compose -f docker-compose-dev.yml up --build
   ```

   ```bash
   docker-compose -f docker-compose-dev.yml down
   ```

4. 애플리케이션 실행하고 브라우저에서 3000 번 포트를 이용해 접속

5. App.js 소스코드 변경

   ```js
   import logo from './logo.svg'
   import './App.css'
   
   function App() {
       return (
           <div className="App">
           	<header className="App-header">
   		        <img src={logo} className="App-logo" alt="logo" />
   				<p>
           			Edit <code>src/App.js</code> and save to reload....
   		        </p>
   		        <a
                       className="App-link"
                       href="https://reactjs.org"
                       target="_blank"
                       ret="noopener noreferrer"
   		        >
           			안녕하세요
   		        </a>
   			</header>
   		</div>
       );
   }
   
   export default App;
   ```

### 6.6 리액트 애플리케이션 테스트하기

#### 도커를 이용한 리액트 애플리케이션에서 테스트를 진행하려면

```bash
docker build -f Dockerfile.dev ./

docker run -it jk/docker-react-app npm run test
```

```js
import React from 'react';
import {render} from '@testing-library/react';
import App from './App';

test('renders learn react link', ()=> {
   const {getByText} = render(<App />);
   const linkElement = getByText(/learn react/i);
   expect(linkElement).toBeInTheDocument();
});

test('renders learn react link', ()=>{
    const { getByText } = render(<App />);
    const linkElement = getByText(/learn react/i);
    expect(linkElement).toBeInTheDocument();
})
```

```yaml
# 도커 컴포즈의 버전
version: "3"
# 실행하는 컨테이너들을 정의
services:
# 서비스 이름
  react:
  # 현 디렉터리에 있는 Dockerfile 사용
    build: 
    # 도커 이미지를 구성하기 위한 파일과 폴더들이 있는 위치
      context: .
      # 도커 파일 어떤 것인지 지정
      dockerfile: Dockerfile.dev
    # 포트 매핑 로컬 포트 : 컨테이너 포트
    ports:
     - "3000:3000"
    # 로컬 머신에 있는 파일들을 매핑
    volumes:
     - /usr/src/app/node_modules
     - ./:/usr/src/app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
# 서비스이름
  tests:
    stdin_open: true
    # 현 디렉터리에 있는 Dockerfile 사용
    build:
      # 도커 이미지를 구성하기 위한 파일들이 있는 위치 
      context: .
      # 도커 파일이 어떤 것인지 지정
      dockerfile: Dockerfile.dev
    # 로컬 머신에 있는 파일을 매핑 
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    #  테스트 컨테이너가 시작될 때 실행되는 명령어
    command: ["npm", "run", "test"]

```

```bash
docker-compose -f docker-compose-dev.yml up --build
```

```js
import React from 'react';
import {render} from '@testing-library/react';
import App from './App';

test('renders learn react link', ()=> {
   const {getByText} = render(<App />);
   const linkElement = getByText(/learn react/i);
   expect(linkElement).toBeInTheDocument();
});

test('renders learn react link', ()=>{
    const { getByText } = render(<App />);
    const linkElement = getByText(/learn react/i);
    expect(linkElement).toBeInTheDocument();
})

test('renders learn react link', ()=>{
    const { getByText } = render(<App />);
    const linkElement = getByText(/learn react/i);
    expect(linkElement).toBeInTheDocument();
})
```



### 6.7 운영 환경을 위한 엔진엑스

#### 개발 환경에서 리액트 애플리케이션이 실행되는 구조

리액트 컨테이너 안에는 개발서버와 정적인 파일들이 있는데. 브라우저에서 리액트 애플리케이션에 접속해 요청이 들어오면 리액트 컨테이너에 있는 개발 서버에서 요청에 알맞게 처리해 정적 파일 전달.

#### 운영 환경에서 리액트 애플리케이션이 실행되는 구조

운영 환경에서 개발 서버 대신에 정적 파일을 제공해주는 역할을 하는 게 바로 엔진엑스 웹 서버.

#### 왜 개발 환경의 서버와 운영 환경의 서버가 다른가요?

개발에서 사용하는 서버는 소스 코드를 변경하면 자동으로 전체 애플리케이션을 다시 빌드해서 변경된
소스 코드를 반영하는 것처럼 개발 환경에 특화된 기능이 있다. 따라서 개발 중에는 이러한 기능이 없는 엔진엑스 서버보다 개발 서버가 더욱 적합. 반대로 운영 환경에서는 소스 코드를 변경할 때 다시 반영할 필요가 없으므로 엔진엑스처럼 더 깔끔하고 빠른 서버를 웹 서버로 사용.



### 6.8 운영 환경의 도커 이미지를 위한 도커 파일 작성하기

#### 개발 환경의 도커 파일과 운영 환경의 도커 파일 비교

#### 운영 환경의 도커 파일 자세히 보기

1. 빌드파일 새성
2. 엑진엑스를 가동하고, 첫 번째 단계에서 생성된 빌드 폴더의 파일들을 웹 브라우저의 요청에 따라 제공

#### 운영 환경에서 리액트 애플리케이션 실행하기

1. 도커 파일 생성 (Dockerfile)

2. 도커 파일 소스 코드 작성

   ```dockerfile
   FROM node:alpine as builder
   WORKDIR '/usr/src/app'
   COPY package.json .
   RUN npm install
   COPY ./ ./
   RUN npm run build
   
   FROM nginx
   COPY --from=builder /usr/src/app/build /usr/share/nginx/html
   ```

3. 도커 파일 이미지 생성

   ```bash
   docker build -t jk/docker-react-app ./
   ```

4. 애플리케이션 실행

   ```bash
   docker run -p 8080:80 jk/docker-react-app
   ```

5. 브라우저에서 애플리케이션 접근



### 6.9 운영 환경의 도커 컴포즈 파일 작성하기

#### 운영 환경의 도커 컴포즈 파일 작성

1. 프로젝트 최상위 디렉터리에 docker-compose.yml 파일 생성

2. 운영 환경의 도커 컴포즈 파일은 개발 환경의 도커 컴포즈 파일과 거의 흡사 
   개발 환경의 도커 컴포즈 파일에 있는 소스 코드를 복사해서 운영 환경 도커 컴포즈 파일 붙여 넣기

3. tests 부분 제거

4. react 컨테이너를 빌드하려면 개발 환경의 도커 파일이 아닌 운영 환경 도커 파일이 필요

5. 포트 변경

   ```yaml
   version: "3"
   services:
     react:
       build: 
         context: .
         dockerfile: Dockerfile
       ports:
        - "80:80"
       volumes:
        - /usr/src/app/node_modules
        - ./:/usr/src/app
       stdin_open: true
   ```
