### ISSUE TITLE
스터디 7주차 인증하기

### ISSUE THREAD

**Issue by LangVE** [daybreak6/docker#7]
## 목표

* 7장. 단일 컨테이너를 활용한 애플리케이션의 테스트와 배포

**Comment by LangVE** [comment]
7장 읽었습니다.

**Comment by kaiwind7** [comment]
## 07. 단일 컨테이너를 활용한 애플리케이션의 테스트와 배포

### 7.1 깃허브에 소스 코드 올리기

1. 깃허브 로그인

2. 저장소 생성

3. 6장 프로젝트 docker-react-app 으로 이동한 다음 로컬 깃 저장소 생성

   ```bash
   git init
   ```

4. 6장 소스 코드를 로컬 깃 저장소에 저장

   ```bash
   // 작업 디렉터리상의 모든 변경 내용을 스테이징 영역에 추가
   git add .
   
   // 스테이징 영역에 있는 소스 코드를 로컬 저장소에 간단한 메시지와 함께 저장
   git commit -m "initial commit"
   ```

   

5. 기본 브랜치 설정

   ```bash
   git branch -M main
   ```

6. 로컬 깃 저장소와 깃허브의 리모트 저장소를 연결
   깃허브 리모트 저장소는 사용자마다 다르게 설정해야 한다. 이 주소는 앞서 생성한 리모트 저장소 페이지에 들어가면 찾을 수 있음.

   ```bash
   git remote add origin https://github.com/kaiwind7/docker-single-app.git
   ```

7. 로컬 깃 저장소에 있는 소스 코드를 깃허브 저장소로 푸시

   ```bash
   git push -u origin main
   ```

   

### 7.2  Travis CI에서 테스트하기 

#### Travis CI란?

Travis CI는 깃허브 및 비트버킷(Bitbucket)에서 호스팅되는 소프트웨어 프로젝트를 빌드하고 테스트 할 수 있는 호스팅 통합 서비스다
Travis CI를 이용하면 깃허브 저장소에 있는 프로젝트를 특정 이벤트에 따라 자동으로 테스트 및 빌드하거나 배포할 수 있다.
Public 저장소는 무료로 사용할 수 있으며, Private 저장소는 일정 금액을 지불하고 사용할 수 있다.

#### Travis CI의 역할

1. 로컬 깃 저장소에 있는 소스 코드를 깃허브 저장에 푸시.
2. 깃허브의 메인 저장소에 소스 코드가 푸시되면 Travis CI가 자동으로 깃허브 저장소에 푸시된 소스 코드를 가져온다.
3. 깃허브에서 가져온 소스 코드 중에서 테스트 코드를 실행
4. 테스트 코드를 실행한 후 테스트에 성공하면 AWS 같은 호스팅 사이트로 소스 코드 배포

#### Travis CI와 깃허브 연동

1. 브라우저에서 Travis CI 홈페이지 이동
2. Travis CI에 로그인
3. Travis CI가 깃허브에 접근하기 위한 권한을 요청하는 페이지가 나오면 [Authorize Travis CI] 버튼을 클릭
4. 만약 다음과 같이 'Please check your email and confirm yout accout' 라는 메시지가 나오면 자신의 이메일로 들어가서 Travis CI에서 보내준 이메일 확인
5. Travis CI에서 테스트 및 배포를 시작하려면 깃허브 앱 통합을 활성화해야 함.
   GitHub Apps Integration 아래에 있는 [Activate] 버튼을 클릭 활성화
6. 깃허브 아이디에 있는 모든 저장소를 Travis CI와 통합하려면 [All repositories]를 선택하고, 특정 저장소만 통합하려면 [Only select repositries] 를 선택.
7. 설정 페이지로 이동
   오른쪽 상단 계정 아이콘 클릭 후 [Setting]
8. 깃허브에 올린 도커 리액트 애플리케이션 저장소 찾기
   [Repositories] 탭에서 앞서 만든 저장소를 선택. 만약 앞서 만든 저장소가 안 보인다면 왼쪽에 있는 [Sync accout] 버튼을 클릭.

도커에서는 이러한 설정을 위해서 도커 컴포즈 파일에 무엇을 할지 작성했다면, Travis CI에서는 .travise.yml 파일에 무엇을 할지 작성

#### 테스트를 위한 Travis CI 설정 파일 장성하기 - travis.yml

#### Travis.yml 파일 자세히 살펴보기

#### .travis,yml 파일 작성하기

1. 먼저 ,travis,yml 파일을 생성

2. ,travis,yml 파일에 다음과 같이 소스 코드를 작성

   ```yaml
   # 관리자 권한 갖기
   sudo: required
   
   # 언어(플랫폼)를 선택
   language: generic
   
   # 도커 환경 구성
   services:
     - docker
   
   # 스크립트를 실행할 수 있는 환경 구성
   before_install:
     - echo "start creating an image with dockerfile"
     - docker build -t jk/docker-react-app -f Dockerfile.dev
     
   # 실행할 스크립트(테스트 실행)
   script: 
     - docker run -e CI=true jk/docker-react-app npm run test -- --coverage
     
   #테스트 성공 후에 할 일
   after_success:
     - echo "Test Success"
   ```

travis,yml 파일을 모두 작성했다면 리액트 애플리케이션 소스 코드를 깃허브에 다시 배포해서 Travis CI가 잘 처리하는 확인

1. 변경된 소스 코드를 깃허브로 푸시

   ```bash
   git add .
   git commit -m "travis.yml file added"
   git push origin main
   ```

2. 소스 코드를 깃허브로 푸시하고 브라우저에서 깃허브 저장소에 접속해 보면 소스 코드가 업데이트된 것을 볼 수 있다.

3. 브라우저에서 Travis CI 사이트 접속
   자동으로 깃허브에서 소스 코드를 가져오고 travis.yml 파일에 설정한 대로 실행되는 모습을 볼 수 있다.

### 7.3 AWS 알아보기

#### AWS 서비스들

#### EC2란 무엇인가?(Elastic Compute Cloud)

#### 일래스틱 빈스톡이란 무엇인가?(Elastic Beanstalk)

일래스틱 빈스톡 서비스는 아파치, 엔진엑스 같은 서버에서 자바, NET, PHP, Node.js, 파이썬, 루비, Go 및 도커와 함께 개발된 웹 애플리케이션이나 서비스를 쉽게 배포하고 확장할 수 있도록 돕는 서비스 입니다.

### 7.4 일래스틱 빈스톡 환경과 애플리케이션 만들기

1. AWS 사이트 이동
2. 로그인
3. AWS 관리 콘솔 페이지 이동
4. 일래스틱 빈스톡 서비스 (Elastic Beanstalk)검색 
5. 일래스틱 빈스톡 페이지 이동

#### 새로운 일래스틱 빈스톡 환경 만들기

1. AWS 관리 콘솔 검색창에서 'Elastic Beanstalk' 으로 검색해 일래스틱 빈스톡 페이지로 이동
2. 새로운 환경을 생성하기 위해 [Create Application] 버튼을 클릭
3. 애플리케이션 정보에서 애플리케이션 이름 지정
   docker-react-app 설정
4. 애플리케이션 플랫폼을 선택
   도커 환경에서 애플리케이션을 실행할 것이므로 플랫폼은 'Docker' 선택
   플랫폼 브랜치는 'Docker running on 64bit Amazon Linux 2' 선택
5. 애플리케이션 코드 선택
   우선 샘플 애플리케이션 선택 시작하고, 나중에 리액트 애플리케이션의 소스 코드를 업로드
6. [애플리케이션 생성] 버튼을 클릭해 환경을 생성
7. 환경 생성 시간 대기
8. 환경이 만들어지면 다음과 같은 화면을 볼 수 있다..

#### 트래픽이 많지 않을 때

#### 트래픽이 많을 때

### 7.5 애플리케이션을 배포하기 위한 Travis CI 설정 파일 작성하기

#### 배포와 관련된 Travis CI 설정 코드

```yaml
# 관리자 권한 갖기
sudo: required

# 언어(플랫폼)를 선택
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트를 실행할 수 있는 환경 구성
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jk/docker-react-app -f Dockerfile.dev
  
# 실행할 스크립트(테스트 실행)
script: 
  - docker run -e CI=true jk/docker-react-app npm run test -- --coverage
  

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
  bucket_path: docker-react-app
  on: 
    branch: main
```



### 7.6 Travis CI에서 AWS에 접근하기 위한 API 생성

#### 소스 코드를 전달하기 위한 접근 요건

#### IAM(Identity and Access Management) 이란?

AWS 리소스에 접근할 때 안전하게 제어할 수 있도록 돕는 웹 서비스

#### IAM 사용자 생성하기

1. AWS 관리 콘솔에서 'IAM' 검색해서 이동
2. 왼쪽 메뉴에서 [엑세스 관리] - [사용자]를 선택
3. 오른쪽에 있는 [사용자 추가] 버튼을 클릭
4. 사용자 세부 정보 설정
   사용자 이름 docker-react-user 로 지정, 엑세스 유형은 '프로그래밍 방식 엑세스' 선택
5. 사용자 권한 설정
   'Administrator Access-AWSElasticBeanstalk'선택
6. IAM 사용자 추가에 성공하면 엑세스 키와 비밀 엑세스 키를 복사

#### API 키를 Travis CI 설정 파일에 작성

1. Travis CI 웹사이트에서 'docker-single-app' 저장소를 선택해 해당 저장소의 대시보드 이동

2. 오른쪽에서 [More options]를 클릭한 다음 [Settings] 선택

3. 환경 변수 항목에 엑세스 키와 비밀 엑세스 키를 입력
   Environment Variables 항목

4. Travis CI 웹사이트에 작성한 키를 로컬 환경에서 가지고 올 수 있게 Travis.yml 파일을 설정

   ```yaml
   deploy: 
     edge: true
     provider: elasticbeanstalk
     region: ap-northeast-2
     app: docker-react-app
     env: DockerReactApp-env
     bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
     bucket_path: docker-react-app
     on: 
       branch: main
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_ACCESS_KEY
   ```

일래스틱 빈스톡을 사용할 때도 외부에서 도커 컨테이너 안에서 실행되는 애플리케이션의 포트에 접근할 수 있게 설정. 애플리케이션이 엔진엑스의 기본 포트인 80번 포트에서 실행되는데, 이를 외부에서 접근할 수 있게 해주려면 도커 파일에 EXPOSE 80 이라고 엔진엑스의 포트 번호를 명시

```dockerfile
...생략...

COPY ./ ./
RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
```



1. 깃허브에 소스 코드 푸시
2. 깃허브 저장소에서 소크 코드 확인
3. Travis CI의 대시보드로 이동해 잘 실행하고 있는지 확인
4. AWS의 일래스틱 빈스톡 환경으로 이동한 다음 애플리케이션이 잘 배포되고 있는지 확인
5. 해당 URL 을 통해서 애플리케이션이 잘 배포됐는지 확인



#### 일래스틱 빈스톡 환경 종료하기

1. 일래스틱 빈스톡 환경 페이지에서 오른쪽에 있는 [작업] 버튼 클릭
2. 작업버튼을 클릭하면 나오는 목록주에서 [환경종료]버튼 클릭
3. 환경의 이름을 입력하고 [종료] 버튼을 클릭
